name: CI Build Check

on:
    push:
        branches-ignore:
            - master
        paths:
            - "apps/frontend/**"
            - "apps/backend/**"
            - "caddy/**"
            - "turbo.json"
            - "package.json"
            - "pnpm-lock.yaml"
            - ".github/workflows/ci.yml"
            - ".github/workflows/build.service.yml"
    pull_request:
        paths:
            - "apps/frontend/**"
            - "apps/backend/**"
            - "caddy/**"
            - "turbo.json"
            - "package.json"
            - "pnpm-lock.yaml"

jobs:
    build-frontend:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
        with:
            service_name: frontend
            filter_paths: |
                - 'apps/frontend/**'
                - 'turbo.json'
                - 'package.json'
                - 'pnpm-lock.yaml'
            dockerfile: apps/frontend/Dockerfile
            context: .
            image_tag: vodka-bio-frontend:ci
            push: false

    build-backend:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
        with:
            service_name: backend
            filter_paths: |
                - 'apps/backend/**'
                - 'turbo.json'
                - 'package.json'
                - 'pnpm-lock.yaml'
            dockerfile: apps/backend/Dockerfile
            context: .
            image_tag: vodka-bio-backend:ci
            push: false

    build-caddy:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
        with:
            service_name: caddy
            filter_paths: |
                - 'caddy/**'
            dockerfile: ./caddy/Dockerfile
            context: ./caddy
            image_tag: vodka-bio-caddy:ci
            push: false
