name: Production Build and Push

on:
    push:
        branches:
            - master
        paths:
            - "apps/frontend/**"
            - "apps/backend/**"
            - "caddy/**"
            - ".github/workflows/deploy.yml"
            - ".github/workflows/build-service.yml"

env:
    IMAGE_BASE: ghcr.io/okiscape/vodka-bio

jobs:
    build-frontend:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
            packages: write
        with:
            service_name: frontend
            filter_paths: |
                src:
                - 'apps/frontend/**'
                - 'turbo.json'
                - 'package.json'
                - 'pnpm-lock.yaml'
            dockerfile: apps/frontend/Dockerfile
            context: .
            image_tag: ghcr.io/okiscape/vodka-bio-frontend:latest
            push: true

    build-backend:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
            packages: write
        with:
            service_name: backend
            filter_paths: |
                src:
                - 'apps/backend/**'
                - 'turbo.json'
                - 'package.json'
                - 'pnpm-lock.yaml'
                - 'package.json'
                - 'pnpm-lock.yaml'
            dockerfile: apps/backend/Dockerfile
            context: .
            image_tag: ghcr.io/okiscape/vodka-bio-backend:latest
            push: true

    build-caddy:
        uses: ./.github/workflows/build.service.yml
        permissions:
            contents: read
            packages: write
        with:
            service_name: caddy
            filter_paths: |
                src:
                    - 'caddy/**'
            dockerfile: ./caddy/Dockerfile
            context: ./caddy
            image_tag: ghcr.io/okiscape/vodka-bio-caddy:latest
            push: true
